# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tracker_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(993, 981)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame = QtGui.QFrame(self.tab_6)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 3, 0, 1, 1)
        self.calibrateButton = QtGui.QPushButton(self.frame)
        self.calibrateButton.setObjectName(_fromUtf8("calibrateButton"))
        self.gridLayout_11.addWidget(self.calibrateButton, 0, 1, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.frame)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.loadcalibrateButton = QtGui.QPushButton(self.groupBox_10)
        self.loadcalibrateButton.setObjectName(_fromUtf8("loadcalibrateButton"))
        self.verticalLayout_8.addWidget(self.loadcalibrateButton)
        self.calibrateVideoLabel = QtGui.QLabel(self.groupBox_10)
        self.calibrateVideoLabel.setObjectName(_fromUtf8("calibrateVideoLabel"))
        self.verticalLayout_8.addWidget(self.calibrateVideoLabel)
        self.gridLayout_11.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.frame)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_12.addWidget(self.label_12, 0, 0, 1, 1)
        self.calTrialIndexLineEdit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calTrialIndexLineEdit.sizePolicy().hasHeightForWidth())
        self.calTrialIndexLineEdit.setSizePolicy(sizePolicy)
        self.calTrialIndexLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.calTrialIndexLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.calTrialIndexLineEdit.setObjectName(_fromUtf8("calTrialIndexLineEdit"))
        self.gridLayout_12.addWidget(self.calTrialIndexLineEdit, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_12.addWidget(self.label_13, 1, 0, 1, 1)
        self.calCamIDLineEdit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calCamIDLineEdit.sizePolicy().hasHeightForWidth())
        self.calCamIDLineEdit.setSizePolicy(sizePolicy)
        self.calCamIDLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.calCamIDLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.calCamIDLineEdit.setObjectName(_fromUtf8("calCamIDLineEdit"))
        self.gridLayout_12.addWidget(self.calCamIDLineEdit, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_12.addWidget(self.label_14, 2, 0, 1, 1)
        self.calDist2pointsLineEdit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calDist2pointsLineEdit.sizePolicy().hasHeightForWidth())
        self.calDist2pointsLineEdit.setSizePolicy(sizePolicy)
        self.calDist2pointsLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.calDist2pointsLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.calDist2pointsLineEdit.setObjectName(_fromUtf8("calDist2pointsLineEdit"))
        self.gridLayout_12.addWidget(self.calDist2pointsLineEdit, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_12.addWidget(self.label_15, 3, 0, 1, 1)
        self.calreferenceLineEdit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calreferenceLineEdit.sizePolicy().hasHeightForWidth())
        self.calreferenceLineEdit.setSizePolicy(sizePolicy)
        self.calreferenceLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.calreferenceLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.calreferenceLineEdit.setObjectName(_fromUtf8("calreferenceLineEdit"))
        self.gridLayout_12.addWidget(self.calreferenceLineEdit, 3, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_6, 1, 0, 1, 2)
        self.groupBox_11 = QtGui.QGroupBox(self.frame)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_16 = QtGui.QLabel(self.groupBox_11)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_13.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_11)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_13.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_11)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_13.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_11)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_13.addWidget(self.label_17, 1, 0, 1, 1)
        self.mpxLabel = QtGui.QLabel(self.groupBox_11)
        self.mpxLabel.setObjectName(_fromUtf8("mpxLabel"))
        self.gridLayout_13.addWidget(self.mpxLabel, 0, 1, 1, 1)
        self.pxmLabel = QtGui.QLabel(self.groupBox_11)
        self.pxmLabel.setObjectName(_fromUtf8("pxmLabel"))
        self.gridLayout_13.addWidget(self.pxmLabel, 1, 1, 1, 1)
        self.distancexLabel = QtGui.QLabel(self.groupBox_11)
        self.distancexLabel.setObjectName(_fromUtf8("distancexLabel"))
        self.gridLayout_13.addWidget(self.distancexLabel, 2, 1, 1, 1)
        self.distanceyLabel = QtGui.QLabel(self.groupBox_11)
        self.distanceyLabel.setObjectName(_fromUtf8("distanceyLabel"))
        self.gridLayout_13.addWidget(self.distanceyLabel, 3, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_11, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 7, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.loadButton = QtGui.QPushButton(self.groupBox_7)
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.gridLayout_8.addWidget(self.loadButton, 0, 0, 1, 1)
        self.previewButton = QtGui.QPushButton(self.groupBox_7)
        self.previewButton.setObjectName(_fromUtf8("previewButton"))
        self.gridLayout_8.addWidget(self.previewButton, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_7)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_8.addWidget(self.label_10, 6, 0, 1, 1)
        self.pathLabel = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pathLabel.setScaledContents(False)
        self.pathLabel.setWordWrap(True)
        self.pathLabel.setObjectName(_fromUtf8("pathLabel"))
        self.gridLayout_8.addWidget(self.pathLabel, 6, 1, 1, 1)
        self.frameratelineEdit = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameratelineEdit.sizePolicy().hasHeightForWidth())
        self.frameratelineEdit.setSizePolicy(sizePolicy)
        self.frameratelineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frameratelineEdit.setObjectName(_fromUtf8("frameratelineEdit"))
        self.gridLayout_8.addWidget(self.frameratelineEdit, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 2, 0, 1, 1)
        self.cameraIdLineEdit = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraIdLineEdit.sizePolicy().hasHeightForWidth())
        self.cameraIdLineEdit.setSizePolicy(sizePolicy)
        self.cameraIdLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cameraIdLineEdit.setObjectName(_fromUtf8("cameraIdLineEdit"))
        self.gridLayout_8.addWidget(self.cameraIdLineEdit, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.novidCheckBox = QtGui.QCheckBox(self.groupBox)
        self.novidCheckBox.setEnabled(True)
        self.novidCheckBox.setChecked(False)
        self.novidCheckBox.setObjectName(_fromUtf8("novidCheckBox"))
        self.gridLayout_2.addWidget(self.novidCheckBox, 2, 1, 1, 1)
        self.outputCheckBox = QtGui.QCheckBox(self.groupBox)
        self.outputCheckBox.setChecked(False)
        self.outputCheckBox.setObjectName(_fromUtf8("outputCheckBox"))
        self.gridLayout_2.addWidget(self.outputCheckBox, 1, 1, 1, 1)
        self.playbackSlider = QtGui.QSlider(self.groupBox)
        self.playbackSlider.setMinimum(10)
        self.playbackSlider.setMaximum(1000)
        self.playbackSlider.setProperty("value", 100)
        self.playbackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playbackSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.playbackSlider.setObjectName(_fromUtf8("playbackSlider"))
        self.gridLayout_2.addWidget(self.playbackSlider, 5, 1, 1, 1)
        self.trackButton = QtGui.QPushButton(self.groupBox)
        self.trackButton.setCheckable(True)
        self.trackButton.setObjectName(_fromUtf8("trackButton"))
        self.gridLayout_2.addWidget(self.trackButton, 3, 1, 1, 1)
        self.label_control_Playback = QtGui.QLabel(self.groupBox)
        self.label_control_Playback.setObjectName(_fromUtf8("label_control_Playback"))
        self.gridLayout_2.addWidget(self.label_control_Playback, 4, 1, 1, 1)
        self.textEdit = QtGui.QTextBrowser(self.groupBox)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_2.addWidget(self.textEdit, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 4, 1, 1)
        self.medianFilterCheckbox = QtGui.QCheckBox(self.groupBox_2)
        self.medianFilterCheckbox.setObjectName(_fromUtf8("medianFilterCheckbox"))
        self.gridLayout_4.addWidget(self.medianFilterCheckbox, 4, 0, 1, 1)
        self.gaussCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.gaussCheckBox.setObjectName(_fromUtf8("gaussCheckBox"))
        self.gridLayout_4.addWidget(self.gaussCheckBox, 1, 0, 1, 1)
        self.backgroundCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.backgroundCheckBox.setChecked(True)
        self.backgroundCheckBox.setObjectName(_fromUtf8("backgroundCheckBox"))
        self.gridLayout_4.addWidget(self.backgroundCheckBox, 2, 0, 1, 1)
        self.gaussSlider = QtGui.QSlider(self.groupBox_2)
        self.gaussSlider.setProperty("value", 0)
        self.gaussSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gaussSlider.setInvertedControls(True)
        self.gaussSlider.setObjectName(_fromUtf8("gaussSlider"))
        self.gridLayout_4.addWidget(self.gaussSlider, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 2, 2, 1, 1)
        self.gaussValueLabel = QtGui.QLabel(self.groupBox_2)
        self.gaussValueLabel.setObjectName(_fromUtf8("gaussValueLabel"))
        self.gridLayout_4.addWidget(self.gaussValueLabel, 1, 2, 1, 1)
        self.removeDigitsCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.removeDigitsCheckBox.setChecked(True)
        self.removeDigitsCheckBox.setObjectName(_fromUtf8("removeDigitsCheckBox"))
        self.gridLayout_4.addWidget(self.removeDigitsCheckBox, 8, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 4, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 1, 3, 1, 1)
        self.kernelSlider = QtGui.QSlider(self.groupBox_2)
        self.kernelSlider.setMinimum(1)
        self.kernelSlider.setMaximum(25)
        self.kernelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.kernelSlider.setObjectName(_fromUtf8("kernelSlider"))
        self.gridLayout_4.addWidget(self.kernelSlider, 7, 1, 1, 1)
        self.kernelValueLabel = QtGui.QLabel(self.groupBox_2)
        self.kernelValueLabel.setObjectName(_fromUtf8("kernelValueLabel"))
        self.gridLayout_4.addWidget(self.kernelValueLabel, 7, 2, 1, 1)
        self.erodeCheckbox = QtGui.QCheckBox(self.groupBox_2)
        self.erodeCheckbox.setObjectName(_fromUtf8("erodeCheckbox"))
        self.gridLayout_4.addWidget(self.erodeCheckbox, 7, 0, 1, 1)
        self.dilateCheckbox = QtGui.QCheckBox(self.groupBox_2)
        self.dilateCheckbox.setObjectName(_fromUtf8("dilateCheckbox"))
        self.gridLayout_4.addWidget(self.dilateCheckbox, 6, 0, 1, 1)
        self.medianValueLabel = QtGui.QLabel(self.groupBox_2)
        self.medianValueLabel.setObjectName(_fromUtf8("medianValueLabel"))
        self.gridLayout_4.addWidget(self.medianValueLabel, 4, 2, 1, 1)
        self.medianSlider = QtGui.QSlider(self.groupBox_2)
        self.medianSlider.setOrientation(QtCore.Qt.Horizontal)
        self.medianSlider.setObjectName(_fromUtf8("medianSlider"))
        self.gridLayout_4.addWidget(self.medianSlider, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 7, 3, 1, 1)
        self.contourLineEdit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contourLineEdit.sizePolicy().hasHeightForWidth())
        self.contourLineEdit.setSizePolicy(sizePolicy)
        self.contourLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.contourLineEdit.setObjectName(_fromUtf8("contourLineEdit"))
        self.gridLayout_4.addWidget(self.contourLineEdit, 0, 0, 1, 1)
        self.contourButton = QtGui.QPushButton(self.groupBox_2)
        self.contourButton.setObjectName(_fromUtf8("contourButton"))
        self.gridLayout_4.addWidget(self.contourButton, 0, 1, 1, 2)
        self.label_6.raise_()
        self.gaussCheckBox.raise_()
        self.medianFilterCheckbox.raise_()
        self.backgroundCheckBox.raise_()
        self.gaussSlider.raise_()
        self.gaussValueLabel.raise_()
        self.dilateCheckbox.raise_()
        self.erodeCheckbox.raise_()
        self.kernelSlider.raise_()
        self.kernelValueLabel.raise_()
        self.medianSlider.raise_()
        self.medianValueLabel.raise_()
        self.removeDigitsCheckBox.raise_()
        self.label_9.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.contourLineEdit.raise_()
        self.contourButton.raise_()
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_12.setEnabled(False)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.enablestitchCheckBox = QtGui.QCheckBox(self.groupBox_12)
        self.enablestitchCheckBox.setObjectName(_fromUtf8("enablestitchCheckBox"))
        self.verticalLayout_9.addWidget(self.enablestitchCheckBox)
        self.stitchDirectoryButton = QtGui.QPushButton(self.groupBox_12)
        self.stitchDirectoryButton.setObjectName(_fromUtf8("stitchDirectoryButton"))
        self.verticalLayout_9.addWidget(self.stitchDirectoryButton)
        self.label_20 = QtGui.QLabel(self.groupBox_12)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_9.addWidget(self.label_20)
        self.populatecameraslineEdit = QtGui.QLineEdit(self.groupBox_12)
        self.populatecameraslineEdit.setObjectName(_fromUtf8("populatecameraslineEdit"))
        self.verticalLayout_9.addWidget(self.populatecameraslineEdit)
        self.stitchButton = QtGui.QPushButton(self.groupBox_12)
        self.stitchButton.setObjectName(_fromUtf8("stitchButton"))
        self.verticalLayout_9.addWidget(self.stitchButton)
        self.gridLayout_6.addWidget(self.groupBox_12, 4, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget = QtGui.QWidget(self.groupBox_3)
        self.widget.setEnabled(False)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_8 = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 175))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.interpolateCheckBox = QtGui.QCheckBox(self.groupBox_5)
        self.interpolateCheckBox.setObjectName(_fromUtf8("interpolateCheckBox"))
        self.gridLayout_14.addWidget(self.interpolateCheckBox, 0, 0, 1, 1)
        self.cropCheckBox = QtGui.QCheckBox(self.groupBox_5)
        self.cropCheckBox.setObjectName(_fromUtf8("cropCheckBox"))
        self.gridLayout_14.addWidget(self.cropCheckBox, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_14.addWidget(self.label_3, 2, 0, 1, 1)
        self.cropstartLineEdit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cropstartLineEdit.sizePolicy().hasHeightForWidth())
        self.cropstartLineEdit.setSizePolicy(sizePolicy)
        self.cropstartLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cropstartLineEdit.setObjectName(_fromUtf8("cropstartLineEdit"))
        self.gridLayout_14.addWidget(self.cropstartLineEdit, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_14.addWidget(self.label_4, 3, 0, 1, 1)
        self.maLabel = QtGui.QLabel(self.groupBox_5)
        self.maLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.maLabel.setObjectName(_fromUtf8("maLabel"))
        self.gridLayout_14.addWidget(self.maLabel, 4, 0, 1, 1)
        self.cropendLineEdit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cropendLineEdit.sizePolicy().hasHeightForWidth())
        self.cropendLineEdit.setSizePolicy(sizePolicy)
        self.cropendLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cropendLineEdit.setObjectName(_fromUtf8("cropendLineEdit"))
        self.gridLayout_14.addWidget(self.cropendLineEdit, 3, 1, 1, 1)
        self.maLineEdit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maLineEdit.sizePolicy().hasHeightForWidth())
        self.maLineEdit.setSizePolicy(sizePolicy)
        self.maLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.maLineEdit.setObjectName(_fromUtf8("maLineEdit"))
        self.gridLayout_14.addWidget(self.maLineEdit, 4, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 0, 2, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.removelonersCheckBox = QtGui.QCheckBox(self.groupBox_13)
        self.removelonersCheckBox.setObjectName(_fromUtf8("removelonersCheckBox"))
        self.gridLayout_15.addWidget(self.removelonersCheckBox, 0, 0, 1, 1)
        self.rSTDCheckBox = QtGui.QCheckBox(self.groupBox_13)
        self.rSTDCheckBox.setObjectName(_fromUtf8("rSTDCheckBox"))
        self.gridLayout_15.addWidget(self.rSTDCheckBox, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_13)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_15.addWidget(self.label_8, 2, 0, 1, 1)
        self.rstd_periods_LineEdit = QtGui.QLineEdit(self.groupBox_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rstd_periods_LineEdit.sizePolicy().hasHeightForWidth())
        self.rstd_periods_LineEdit.setSizePolicy(sizePolicy)
        self.rstd_periods_LineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rstd_periods_LineEdit.setObjectName(_fromUtf8("rstd_periods_LineEdit"))
        self.gridLayout_15.addWidget(self.rstd_periods_LineEdit, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_13)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_15.addWidget(self.label_7, 3, 0, 1, 1)
        self.rstd_threshold_LineEdit = QtGui.QLineEdit(self.groupBox_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rstd_threshold_LineEdit.sizePolicy().hasHeightForWidth())
        self.rstd_threshold_LineEdit.setSizePolicy(sizePolicy)
        self.rstd_threshold_LineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rstd_threshold_LineEdit.setObjectName(_fromUtf8("rstd_threshold_LineEdit"))
        self.gridLayout_15.addWidget(self.rstd_threshold_LineEdit, 3, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_13, 0, 0, 1, 1)
        self.reloadButton = QtGui.QPushButton(self.groupBox_8)
        self.reloadButton.setObjectName(_fromUtf8("reloadButton"))
        self.gridLayout_9.addWidget(self.reloadButton, 7, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.graphicsView = QtGui.QGraphicsView(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 180))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.rawDataTable = QtGui.QTableWidget(self.tab_3)
        self.rawDataTable.setObjectName(_fromUtf8("rawDataTable"))
        self.rawDataTable.setColumnCount(0)
        self.rawDataTable.setRowCount(0)
        self.verticalLayout_6.addWidget(self.rawDataTable)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.treatedDataTable = QtGui.QTableWidget(self.tab_4)
        self.treatedDataTable.setObjectName(_fromUtf8("treatedDataTable"))
        self.treatedDataTable.setColumnCount(0)
        self.treatedDataTable.setRowCount(0)
        self.verticalLayout_7.addWidget(self.treatedDataTable)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.calibrateButton.setText(_translate("MainWindow", "Calibrate", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Video", None))
        self.loadcalibrateButton.setText(_translate("MainWindow", "Load video for calibration", None))
        self.calibrateVideoLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Parameters", None))
        self.label_12.setText(_translate("MainWindow", "Enter trial index:", None))
        self.label_13.setText(_translate("MainWindow", "Enter camera ID:", None))
        self.label_14.setText(_translate("MainWindow", "Distance between points 1 and 2 (m):", None))
        self.label_15.setText(_translate("MainWindow", "Distance of known point to reference point:", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Output", None))
        self.label_16.setText(_translate("MainWindow", "m/px:", None))
        self.label_19.setText(_translate("MainWindow", "Distance in the y (m) of points 1 and 2 from reference point:", None))
        self.label_18.setText(_translate("MainWindow", "Distance in the x (m) of points 1 and 2 from reference point:", None))
        self.label_17.setText(_translate("MainWindow", "px/m:", None))
        self.mpxLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.pxmLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.distancexLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.distanceyLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Calibration", None))
        self.groupBox.setTitle(_translate("MainWindow", "Video", None))
        self.label_21.setText(_translate("MainWindow", "Help box:", None))
        self.groupBox_7.setToolTip(_translate("MainWindow", "Video loading functions", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Video loading", None))
        self.loadButton.setText(_translate("MainWindow", "Load Video", None))
        self.previewButton.setText(_translate("MainWindow", "Fast Preview", None))
        self.label_10.setText(_translate("MainWindow", "Video path:", None))
        self.pathLabel.setText(_translate("MainWindow", "No video loaded", None))
        self.frameratelineEdit.setToolTip(_translate("MainWindow", "set to 27 fps by default", None))
        self.frameratelineEdit.setText(_translate("MainWindow", "27", None))
        self.frameratelineEdit.setPlaceholderText(_translate("MainWindow", "Enter framerate", None))
        self.label_2.setText(_translate("MainWindow", "Framerate", None))
        self.label_11.setText(_translate("MainWindow", "Camera ID:", None))
        self.cameraIdLineEdit.setToolTip(_translate("MainWindow", "Enter camera ID (ex. last two digits of IP address)", None))
        self.cameraIdLineEdit.setText(_translate("MainWindow", "10", None))
        self.cameraIdLineEdit.setPlaceholderText(_translate("MainWindow", "10", None))
        self.novidCheckBox.setToolTip(_translate("MainWindow", "Will track video, produce an output file if \"Produce output files\" is checked but will not show the video tracking.", None))
        self.novidCheckBox.setText(_translate("MainWindow", "Surpress video", None))
        self.outputCheckBox.setText(_translate("MainWindow", "Produce output files", None))
        self.playbackSlider.setToolTip(_translate("MainWindow", "Speed up or slow down video", None))
        self.trackButton.setToolTip(_translate("MainWindow", "Starts object tracking on currently loaded video.", None))
        self.trackButton.setText(_translate("MainWindow", "Track", None))
        self.label_control_Playback.setText(_translate("MainWindow", "Control video playback speed:", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Video processing", None))
        self.groupBox_2.setToolTip(_translate("MainWindow", "Lower limit for detectable contour area in pixels", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filters", None))
        self.medianFilterCheckbox.setToolTip(_translate("MainWindow", "Removes fuzzy noise (slow)", None))
        self.medianFilterCheckbox.setText(_translate("MainWindow", "Apply median filter", None))
        self.gaussCheckBox.setToolTip(_translate("MainWindow", "Smooth out image", None))
        self.gaussCheckBox.setText(_translate("MainWindow", "Use Guassian blur", None))
        self.backgroundCheckBox.setToolTip(_translate("MainWindow", "Necessary for tracking", None))
        self.backgroundCheckBox.setText(_translate("MainWindow", "Apply MOG", None))
        self.gaussSlider.setToolTip(_translate("MainWindow", "Reduce with noise with Gaussian filter", None))
        self.gaussValueLabel.setText(_translate("MainWindow", "0", None))
        self.removeDigitsCheckBox.setToolTip(_translate("MainWindow", "Reduce false detections because of time stamp", None))
        self.removeDigitsCheckBox.setText(_translate("MainWindow", "Remove white digits", None))
        self.label.setText(_translate("MainWindow", "px", None))
        self.label_9.setText(_translate("MainWindow", "px", None))
        self.kernelSlider.setToolTip(_translate("MainWindow", "Choose kernel size for dilate and erode", None))
        self.kernelValueLabel.setText(_translate("MainWindow", "0", None))
        self.erodeCheckbox.setToolTip(_translate("MainWindow", "Useful to erode away noise", None))
        self.erodeCheckbox.setText(_translate("MainWindow", "Erode", None))
        self.dilateCheckbox.setToolTip(_translate("MainWindow", "Useful to increase size of small objects", None))
        self.dilateCheckbox.setText(_translate("MainWindow", "Dilate", None))
        self.medianValueLabel.setText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "px", None))
        self.contourLineEdit.setToolTip(_translate("MainWindow", "Default is 100", None))
        self.contourLineEdit.setText(_translate("MainWindow", "100", None))
        self.contourButton.setText(_translate("MainWindow", "Reset contour area limit", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Stitch", None))
        self.enablestitchCheckBox.setToolTip(_translate("MainWindow", "Allows user to stitch together kinematics data from multiple cameras. Tip - perform error removal on each individual camera beforehand.", None))
        self.enablestitchCheckBox.setText(_translate("MainWindow", "Enable multi-camera stitching", None))
        self.stitchDirectoryButton.setText(_translate("MainWindow", "Select directory", None))
        self.label_20.setText(_translate("MainWindow", "Enter Camera IDs:", None))
        self.stitchButton.setText(_translate("MainWindow", "Stitch", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Plotting", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Post-processing", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Interpolation and cropping", None))
        self.interpolateCheckBox.setText(_translate("MainWindow", "Interpolate missing values", None))
        self.cropCheckBox.setText(_translate("MainWindow", "Crop output", None))
        self.label_3.setText(_translate("MainWindow", "Start Frame:", None))
        self.cropstartLineEdit.setText(_translate("MainWindow", "0", None))
        self.label_4.setText(_translate("MainWindow", "End Frame:", None))
        self.maLabel.setText(_translate("MainWindow", "MA periods:", None))
        self.cropendLineEdit.setText(_translate("MainWindow", "0", None))
        self.maLineEdit.setToolTip(_translate("MainWindow", "Number of periods for the moving averages", None))
        self.maLineEdit.setText(_translate("MainWindow", "10", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Error removal", None))
        self.removelonersCheckBox.setText(_translate("MainWindow", "Remove lone values", None))
        self.rSTDCheckBox.setText(_translate("MainWindow", "Perform rSTD removal", None))
        self.label_8.setText(_translate("MainWindow", "rSTD periods", None))
        self.label_7.setText(_translate("MainWindow", "rSTD threshold", None))
        self.reloadButton.setText(_translate("MainWindow", "Refresh plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tracking", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Raw Pixel Coordinates", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Post-processed Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tables", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))

