# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tracker_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1032, 690)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame = QtGui.QFrame(self.tab_6)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox_11 = QtGui.QGroupBox(self.frame)
        self.groupBox_11.setEnabled(False)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_23 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.calLoadCalibrate_B = QtGui.QPushButton(self.groupBox_11)
        self.calLoadCalibrate_B.setObjectName(_fromUtf8("calLoadCalibrate_B"))
        self.gridLayout_23.addWidget(self.calLoadCalibrate_B, 1, 0, 1, 1)
        self.cal_LW = QtGui.QListWidget(self.groupBox_11)
        self.cal_LW.setObjectName(_fromUtf8("cal_LW"))
        self.gridLayout_23.addWidget(self.cal_LW, 1, 1, 1, 1)
        self.calVideo_L = QtGui.QLabel(self.groupBox_11)
        self.calVideo_L.setText(_fromUtf8(""))
        self.calVideo_L.setObjectName(_fromUtf8("calVideo_L"))
        self.gridLayout_23.addWidget(self.calVideo_L, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_11)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_23.addWidget(self.label_16, 2, 0, 1, 1)
        self.calRectify_B = QtGui.QPushButton(self.groupBox_11)
        self.calRectify_B.setObjectName(_fromUtf8("calRectify_B"))
        self.gridLayout_23.addWidget(self.calRectify_B, 4, 0, 1, 1)
        self.calRectify_CB = QtGui.QCheckBox(self.groupBox_11)
        self.calRectify_CB.setChecked(True)
        self.calRectify_CB.setObjectName(_fromUtf8("calRectify_CB"))
        self.gridLayout_23.addWidget(self.calRectify_CB, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_11)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_23.addWidget(self.label_8, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_11, 3, 0, 1, 2)
        self.calParameters_GB = QtGui.QGroupBox(self.frame)
        self.calParameters_GB.setEnabled(False)
        self.calParameters_GB.setObjectName(_fromUtf8("calParameters_GB"))
        self.gridLayout_12 = QtGui.QGridLayout(self.calParameters_GB)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.cameraID_LE = QtGui.QLineEdit(self.calParameters_GB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraID_LE.sizePolicy().hasHeightForWidth())
        self.cameraID_LE.setSizePolicy(sizePolicy)
        self.cameraID_LE.setMinimumSize(QtCore.QSize(100, 0))
        self.cameraID_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.cameraID_LE.setObjectName(_fromUtf8("cameraID_LE"))
        self.gridLayout_12.addWidget(self.cameraID_LE, 2, 1, 1, 1)
        self.calMakeCalFile_B = QtGui.QPushButton(self.calParameters_GB)
        self.calMakeCalFile_B.setObjectName(_fromUtf8("calMakeCalFile_B"))
        self.gridLayout_12.addWidget(self.calMakeCalFile_B, 5, 1, 1, 1)
        self.distance2pnts_LE = QtGui.QLineEdit(self.calParameters_GB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distance2pnts_LE.sizePolicy().hasHeightForWidth())
        self.distance2pnts_LE.setSizePolicy(sizePolicy)
        self.distance2pnts_LE.setMinimumSize(QtCore.QSize(100, 0))
        self.distance2pnts_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.distance2pnts_LE.setObjectName(_fromUtf8("distance2pnts_LE"))
        self.gridLayout_12.addWidget(self.distance2pnts_LE, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.calParameters_GB)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_12.addWidget(self.label_15, 4, 0, 1, 1)
        self.trialIndex_LE = QtGui.QLineEdit(self.calParameters_GB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialIndex_LE.sizePolicy().hasHeightForWidth())
        self.trialIndex_LE.setSizePolicy(sizePolicy)
        self.trialIndex_LE.setMinimumSize(QtCore.QSize(100, 0))
        self.trialIndex_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.trialIndex_LE.setObjectName(_fromUtf8("trialIndex_LE"))
        self.gridLayout_12.addWidget(self.trialIndex_LE, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.calParameters_GB)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_12.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.calParameters_GB)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_12.addWidget(self.label_13, 2, 0, 1, 1)
        self.refDistance_LE = QtGui.QLineEdit(self.calParameters_GB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refDistance_LE.sizePolicy().hasHeightForWidth())
        self.refDistance_LE.setSizePolicy(sizePolicy)
        self.refDistance_LE.setMinimumSize(QtCore.QSize(100, 0))
        self.refDistance_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.refDistance_LE.setObjectName(_fromUtf8("refDistance_LE"))
        self.gridLayout_12.addWidget(self.refDistance_LE, 4, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.calParameters_GB)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_12.addWidget(self.label_12, 1, 0, 1, 1)
        self.calCalibrate_B = QtGui.QPushButton(self.calParameters_GB)
        self.calCalibrate_B.setObjectName(_fromUtf8("calCalibrate_B"))
        self.gridLayout_12.addWidget(self.calCalibrate_B, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.calParameters_GB, 5, 0, 1, 2)
        self.groupBox_12 = QtGui.QGroupBox(self.frame)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_22 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.calLabelPath_L = QtGui.QLabel(self.groupBox_12)
        self.calLabelPath_L.setObjectName(_fromUtf8("calLabelPath_L"))
        self.gridLayout_22.addWidget(self.calLabelPath_L, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_12)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_22.addWidget(self.label_20, 1, 0, 1, 1)
        self.calChosepath_B = QtGui.QPushButton(self.groupBox_12)
        self.calChosepath_B.setObjectName(_fromUtf8("calChosepath_B"))
        self.gridLayout_22.addWidget(self.calChosepath_B, 0, 0, 1, 2)
        self.gridLayout_11.addWidget(self.groupBox_12, 0, 0, 1, 2)
        self.groupBox_10 = QtGui.QGroupBox(self.frame)
        self.groupBox_10.setEnabled(True)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_10)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_13.addWidget(self.checkBox_2, 0, 0, 1, 1)
        self.calChoseExisting_B = QtGui.QPushButton(self.groupBox_10)
        self.calChoseExisting_B.setEnabled(True)
        self.calChoseExisting_B.setObjectName(_fromUtf8("calChoseExisting_B"))
        self.gridLayout_13.addWidget(self.calChoseExisting_B, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_10, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 6, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 2, 1, 1, 1)
        self.cal_TE = QtGui.QTextEdit(self.tab_6)
        self.cal_TE.setObjectName(_fromUtf8("cal_TE"))
        self.gridLayout_7.addWidget(self.cal_TE, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tab_6)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_7.addWidget(self.pushButton, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.trkLoad_B = QtGui.QPushButton(self.groupBox_7)
        self.trkLoad_B.setObjectName(_fromUtf8("trkLoad_B"))
        self.gridLayout_8.addWidget(self.trkLoad_B, 0, 0, 1, 1)
        self.trkPreview_B = QtGui.QPushButton(self.groupBox_7)
        self.trkPreview_B.setObjectName(_fromUtf8("trkPreview_B"))
        self.gridLayout_8.addWidget(self.trkPreview_B, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_7)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_8.addWidget(self.label_10, 6, 0, 1, 1)
        self.pathLabel = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pathLabel.setScaledContents(False)
        self.pathLabel.setWordWrap(True)
        self.pathLabel.setObjectName(_fromUtf8("pathLabel"))
        self.gridLayout_8.addWidget(self.pathLabel, 6, 1, 1, 1)
        self.trkFramerate_LE = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trkFramerate_LE.sizePolicy().hasHeightForWidth())
        self.trkFramerate_LE.setSizePolicy(sizePolicy)
        self.trkFramerate_LE.setMaximumSize(QtCore.QSize(40, 16777215))
        self.trkFramerate_LE.setObjectName(_fromUtf8("trkFramerate_LE"))
        self.gridLayout_8.addWidget(self.trkFramerate_LE, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 2, 0, 1, 1)
        self.cameraIdLineEdit = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraIdLineEdit.sizePolicy().hasHeightForWidth())
        self.cameraIdLineEdit.setSizePolicy(sizePolicy)
        self.cameraIdLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cameraIdLineEdit.setObjectName(_fromUtf8("cameraIdLineEdit"))
        self.gridLayout_8.addWidget(self.cameraIdLineEdit, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 6, 1, 1, 1)
        self.novidCheckBox = QtGui.QCheckBox(self.groupBox)
        self.novidCheckBox.setEnabled(True)
        self.novidCheckBox.setChecked(False)
        self.novidCheckBox.setObjectName(_fromUtf8("novidCheckBox"))
        self.gridLayout_2.addWidget(self.novidCheckBox, 1, 1, 1, 1)
        self.label_control_Playback = QtGui.QLabel(self.groupBox)
        self.label_control_Playback.setObjectName(_fromUtf8("label_control_Playback"))
        self.gridLayout_2.addWidget(self.label_control_Playback, 3, 1, 1, 1)
        self.track_TE = QtGui.QTextBrowser(self.groupBox)
        self.track_TE.setObjectName(_fromUtf8("track_TE"))
        self.gridLayout_2.addWidget(self.track_TE, 5, 1, 1, 1)
        self.trkTrack_B = QtGui.QPushButton(self.groupBox)
        self.trkTrack_B.setCheckable(True)
        self.trkTrack_B.setObjectName(_fromUtf8("trkTrack_B"))
        self.gridLayout_2.addWidget(self.trkTrack_B, 2, 1, 1, 1)
        self.playbackSlider = QtGui.QSlider(self.groupBox)
        self.playbackSlider.setMinimum(10)
        self.playbackSlider.setMaximum(1000)
        self.playbackSlider.setProperty("value", 950)
        self.playbackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playbackSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.playbackSlider.setObjectName(_fromUtf8("playbackSlider"))
        self.gridLayout_2.addWidget(self.playbackSlider, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 4, 1, 1)
        self.medianFilterCheckbox = QtGui.QCheckBox(self.groupBox_2)
        self.medianFilterCheckbox.setObjectName(_fromUtf8("medianFilterCheckbox"))
        self.gridLayout_4.addWidget(self.medianFilterCheckbox, 4, 0, 1, 1)
        self.gaussCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.gaussCheckBox.setObjectName(_fromUtf8("gaussCheckBox"))
        self.gridLayout_4.addWidget(self.gaussCheckBox, 1, 0, 1, 1)
        self.backgroundCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.backgroundCheckBox.setChecked(True)
        self.backgroundCheckBox.setObjectName(_fromUtf8("backgroundCheckBox"))
        self.gridLayout_4.addWidget(self.backgroundCheckBox, 2, 0, 1, 1)
        self.gaussSlider = QtGui.QSlider(self.groupBox_2)
        self.gaussSlider.setProperty("value", 0)
        self.gaussSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gaussSlider.setInvertedControls(True)
        self.gaussSlider.setObjectName(_fromUtf8("gaussSlider"))
        self.gridLayout_4.addWidget(self.gaussSlider, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 2, 2, 1, 1)
        self.gaussValueLabel = QtGui.QLabel(self.groupBox_2)
        self.gaussValueLabel.setObjectName(_fromUtf8("gaussValueLabel"))
        self.gridLayout_4.addWidget(self.gaussValueLabel, 1, 2, 1, 1)
        self.removeDigitsCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.removeDigitsCheckBox.setChecked(True)
        self.removeDigitsCheckBox.setObjectName(_fromUtf8("removeDigitsCheckBox"))
        self.gridLayout_4.addWidget(self.removeDigitsCheckBox, 8, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 4, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 1, 3, 1, 1)
        self.kernelSlider = QtGui.QSlider(self.groupBox_2)
        self.kernelSlider.setMinimum(1)
        self.kernelSlider.setMaximum(25)
        self.kernelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.kernelSlider.setObjectName(_fromUtf8("kernelSlider"))
        self.gridLayout_4.addWidget(self.kernelSlider, 7, 1, 1, 1)
        self.kernelValueLabel = QtGui.QLabel(self.groupBox_2)
        self.kernelValueLabel.setObjectName(_fromUtf8("kernelValueLabel"))
        self.gridLayout_4.addWidget(self.kernelValueLabel, 7, 2, 1, 1)
        self.erodeCheckbox = QtGui.QCheckBox(self.groupBox_2)
        self.erodeCheckbox.setObjectName(_fromUtf8("erodeCheckbox"))
        self.gridLayout_4.addWidget(self.erodeCheckbox, 7, 0, 1, 1)
        self.dilateCheckbox = QtGui.QCheckBox(self.groupBox_2)
        self.dilateCheckbox.setObjectName(_fromUtf8("dilateCheckbox"))
        self.gridLayout_4.addWidget(self.dilateCheckbox, 6, 0, 1, 1)
        self.medianValueLabel = QtGui.QLabel(self.groupBox_2)
        self.medianValueLabel.setObjectName(_fromUtf8("medianValueLabel"))
        self.gridLayout_4.addWidget(self.medianValueLabel, 4, 2, 1, 1)
        self.medianSlider = QtGui.QSlider(self.groupBox_2)
        self.medianSlider.setOrientation(QtCore.Qt.Horizontal)
        self.medianSlider.setObjectName(_fromUtf8("medianSlider"))
        self.gridLayout_4.addWidget(self.medianSlider, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 7, 3, 1, 1)
        self.contourLineEdit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contourLineEdit.sizePolicy().hasHeightForWidth())
        self.contourLineEdit.setSizePolicy(sizePolicy)
        self.contourLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.contourLineEdit.setObjectName(_fromUtf8("contourLineEdit"))
        self.gridLayout_4.addWidget(self.contourLineEdit, 0, 0, 1, 1)
        self.trkContour_B = QtGui.QPushButton(self.groupBox_2)
        self.trkContour_B.setObjectName(_fromUtf8("trkContour_B"))
        self.gridLayout_4.addWidget(self.trkContour_B, 0, 1, 1, 2)
        self.label_6.raise_()
        self.gaussCheckBox.raise_()
        self.medianFilterCheckbox.raise_()
        self.backgroundCheckBox.raise_()
        self.gaussSlider.raise_()
        self.gaussValueLabel.raise_()
        self.dilateCheckbox.raise_()
        self.erodeCheckbox.raise_()
        self.kernelSlider.raise_()
        self.kernelValueLabel.raise_()
        self.medianSlider.raise_()
        self.medianValueLabel.raise_()
        self.removeDigitsCheckBox.raise_()
        self.label_9.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.contourLineEdit.raise_()
        self.trkContour_B.raise_()
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_9.setEnabled(True)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget_2 = QtGui.QWidget(self.groupBox_9)
        self.widget_2.setEnabled(True)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.groupBox_15 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_15)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.ppBlank_B = QtGui.QPushButton(self.groupBox_15)
        self.ppBlank_B.setObjectName(_fromUtf8("ppBlank_B"))
        self.gridLayout_16.addWidget(self.ppBlank_B, 0, 0, 1, 1)
        self.ppUndo_B = QtGui.QPushButton(self.groupBox_15)
        self.ppUndo_B.setObjectName(_fromUtf8("ppUndo_B"))
        self.gridLayout_16.addWidget(self.ppUndo_B, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_15, 3, 1, 1, 1)
        self.groupBox_16 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_16.setEnabled(False)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.removelonersCheckBox_2 = QtGui.QCheckBox(self.groupBox_16)
        self.removelonersCheckBox_2.setObjectName(_fromUtf8("removelonersCheckBox_2"))
        self.gridLayout_15.addWidget(self.removelonersCheckBox_2, 0, 0, 1, 1)
        self.rSTDCheckBox_2 = QtGui.QCheckBox(self.groupBox_16)
        self.rSTDCheckBox_2.setObjectName(_fromUtf8("rSTDCheckBox_2"))
        self.gridLayout_15.addWidget(self.rSTDCheckBox_2, 1, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_16)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_15.addWidget(self.label_24, 2, 0, 1, 1)
        self.rstd_periods_LineEdit_2 = QtGui.QLineEdit(self.groupBox_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rstd_periods_LineEdit_2.sizePolicy().hasHeightForWidth())
        self.rstd_periods_LineEdit_2.setSizePolicy(sizePolicy)
        self.rstd_periods_LineEdit_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rstd_periods_LineEdit_2.setObjectName(_fromUtf8("rstd_periods_LineEdit_2"))
        self.gridLayout_15.addWidget(self.rstd_periods_LineEdit_2, 2, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_16)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_15.addWidget(self.label_25, 3, 0, 1, 1)
        self.rstd_threshold_LineEdit_2 = QtGui.QLineEdit(self.groupBox_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rstd_threshold_LineEdit_2.sizePolicy().hasHeightForWidth())
        self.rstd_threshold_LineEdit_2.setSizePolicy(sizePolicy)
        self.rstd_threshold_LineEdit_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rstd_threshold_LineEdit_2.setObjectName(_fromUtf8("rstd_threshold_LineEdit_2"))
        self.gridLayout_15.addWidget(self.rstd_threshold_LineEdit_2, 3, 1, 1, 1)
        self.ppExecute_B = QtGui.QPushButton(self.groupBox_16)
        self.ppExecute_B.setObjectName(_fromUtf8("ppExecute_B"))
        self.gridLayout_15.addWidget(self.ppExecute_B, 4, 0, 1, 2)
        self.gridLayout_10.addWidget(self.groupBox_16, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.ppFileLoaded_L = QtGui.QLabel(self.groupBox_3)
        self.ppFileLoaded_L.setObjectName(_fromUtf8("ppFileLoaded_L"))
        self.gridLayout_3.addWidget(self.ppFileLoaded_L, 3, 0, 1, 1)
        self.csvList_LW = QtGui.QListWidget(self.groupBox_3)
        self.csvList_LW.setObjectName(_fromUtf8("csvList_LW"))
        self.gridLayout_3.addWidget(self.csvList_LW, 1, 1, 1, 1)
        self.ppFileOpen_B = QtGui.QPushButton(self.groupBox_3)
        self.ppFileOpen_B.setObjectName(_fromUtf8("ppFileOpen_B"))
        self.gridLayout_3.addWidget(self.ppFileOpen_B, 1, 0, 1, 1)
        self.ppClean_B = QtGui.QPushButton(self.groupBox_3)
        self.ppClean_B.setObjectName(_fromUtf8("ppClean_B"))
        self.gridLayout_3.addWidget(self.ppClean_B, 3, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.tabWidget_3 = QtGui.QTabWidget(self.widget_2)
        self.tabWidget_3.setUsesScrollButtons(False)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_19 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.ppAdjust_B = QtGui.QPushButton(self.groupBox_13)
        self.ppAdjust_B.setObjectName(_fromUtf8("ppAdjust_B"))
        self.gridLayout_18.addWidget(self.ppAdjust_B, 4, 0, 1, 2)
        self.ppSubtract_RB = QtGui.QRadioButton(self.groupBox_13)
        self.ppSubtract_RB.setObjectName(_fromUtf8("ppSubtract_RB"))
        self.gridLayout_18.addWidget(self.ppSubtract_RB, 1, 1, 1, 1)
        self.ppAdjust_LE = QtGui.QLineEdit(self.groupBox_13)
        self.ppAdjust_LE.setPlaceholderText(_fromUtf8(""))
        self.ppAdjust_LE.setObjectName(_fromUtf8("ppAdjust_LE"))
        self.gridLayout_18.addWidget(self.ppAdjust_LE, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_13)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_18.addWidget(self.label_7, 0, 0, 1, 1)
        self.ppAdd_RB = QtGui.QRadioButton(self.groupBox_13)
        self.ppAdd_RB.setChecked(True)
        self.ppAdd_RB.setObjectName(_fromUtf8("ppAdd_RB"))
        self.gridLayout_18.addWidget(self.ppAdd_RB, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_13, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_20 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.ppStitch_B = QtGui.QPushButton(self.groupBox_8)
        self.ppStitch_B.setEnabled(True)
        self.ppStitch_B.setObjectName(_fromUtf8("ppStitch_B"))
        self.gridLayout_17.addWidget(self.ppStitch_B, 1, 1, 1, 1)
        self.ppHorizontalCombine_B = QtGui.QPushButton(self.groupBox_8)
        self.ppHorizontalCombine_B.setEnabled(True)
        self.ppHorizontalCombine_B.setObjectName(_fromUtf8("ppHorizontalCombine_B"))
        self.gridLayout_17.addWidget(self.ppHorizontalCombine_B, 0, 1, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.gridLayout_21 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.ppInterpolate_B = QtGui.QPushButton(self.groupBox_5)
        self.ppInterpolate_B.setObjectName(_fromUtf8("ppInterpolate_B"))
        self.gridLayout_9.addWidget(self.ppInterpolate_B, 1, 1, 1, 1)
        self.cropstartLineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.cropstartLineEdit_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cropstartLineEdit_2.sizePolicy().hasHeightForWidth())
        self.cropstartLineEdit_2.setSizePolicy(sizePolicy)
        self.cropstartLineEdit_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cropstartLineEdit_2.setObjectName(_fromUtf8("cropstartLineEdit_2"))
        self.gridLayout_9.addWidget(self.cropstartLineEdit_2, 4, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setEnabled(False)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_9.addWidget(self.label_22, 4, 0, 1, 1)
        self.maLineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.maLineEdit_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maLineEdit_2.sizePolicy().hasHeightForWidth())
        self.maLineEdit_2.setSizePolicy(sizePolicy)
        self.maLineEdit_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.maLineEdit_2.setObjectName(_fromUtf8("maLineEdit_2"))
        self.gridLayout_9.addWidget(self.maLineEdit_2, 6, 1, 1, 1)
        self.maLabel_2 = QtGui.QLabel(self.groupBox_5)
        self.maLabel_2.setEnabled(False)
        self.maLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.maLabel_2.setObjectName(_fromUtf8("maLabel_2"))
        self.gridLayout_9.addWidget(self.maLabel_2, 6, 0, 1, 1)
        self.cropendLineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.cropendLineEdit_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cropendLineEdit_2.sizePolicy().hasHeightForWidth())
        self.cropendLineEdit_2.setSizePolicy(sizePolicy)
        self.cropendLineEdit_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cropendLineEdit_2.setObjectName(_fromUtf8("cropendLineEdit_2"))
        self.gridLayout_9.addWidget(self.cropendLineEdit_2, 5, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setEnabled(False)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_9.addWidget(self.label_23, 5, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget_3, 4, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.gridLayout_14.addWidget(self.groupBox_9, 0, 0, 2, 1)
        self.pp_TV = QtGui.QTableView(self.tab_5)
        self.pp_TV.setObjectName(_fromUtf8("pp_TV"))
        self.gridLayout_14.addWidget(self.pp_TV, 0, 1, 1, 1)
        self.plot_L = QtGui.QLabel(self.tab_5)
        self.plot_L.setObjectName(_fromUtf8("plot_L"))
        self.gridLayout_14.addWidget(self.plot_L, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.activePath_L = QtGui.QLabel(self.centralwidget)
        self.activePath_L.setObjectName(_fromUtf8("activePath_L"))
        self.gridLayout.addWidget(self.activePath_L, 2, 0, 1, 1)
        self.projectPath_L = QtGui.QLabel(self.centralwidget)
        self.projectPath_L.setObjectName(_fromUtf8("projectPath_L"))
        self.gridLayout.addWidget(self.projectPath_L, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setEnabled(False)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setEnabled(False)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.calChoseExisting_B.setEnabled)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_11.setDisabled)
        QtCore.QObject.connect(self.calRectify_CB, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.calRectify_B.setEnabled)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.calChoseExisting_B.setEnabled)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.calParameters_GB.setDisabled)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cal_TE.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Define new calibration:", None))
        self.calLoadCalibrate_B.setText(_translate("MainWindow", "Load Video", None))
        self.label_16.setText(_translate("MainWindow", "Active video for calibration:", None))
        self.calRectify_B.setToolTip(_translate("MainWindow", "Input three points to define rotation angle. Choose points 1 and 2 so they lie along a horiztonal line. Chose point three so that it shares the same x coordinate as point 1. ", None))
        self.calRectify_B.setStatusTip(_translate("MainWindow", "Rectify Image: Points 1 and 2 should lie along a straight line. Point 3 should be at the same x coordinate as point 1, but at a different y.", None))
        self.calRectify_B.setText(_translate("MainWindow", "Rectify", None))
        self.calRectify_CB.setStatusTip(_translate("MainWindow", "Select to rectify image before calibration", None))
        self.calRectify_CB.setText(_translate("MainWindow", "Rectify image for camera angle", None))
        self.label_8.setText(_translate("MainWindow", "Select calibration to modify:", None))
        self.calParameters_GB.setTitle(_translate("MainWindow", "Calibration Parameters", None))
        self.calMakeCalFile_B.setText(_translate("MainWindow", "Make calibration files", None))
        self.label_15.setText(_translate("MainWindow", "Distance of known point to reference point:", None))
        self.label_14.setText(_translate("MainWindow", "Distance between points 1 and 2 (m):", None))
        self.label_13.setText(_translate("MainWindow", "Enter camera ID:", None))
        self.label_12.setText(_translate("MainWindow", "Enter trial index:", None))
        self.calCalibrate_B.setText(_translate("MainWindow", "Calibrate selected video", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Chose project path:", None))
        self.calLabelPath_L.setText(_translate("MainWindow", "No path specified", None))
        self.label_20.setText(_translate("MainWindow", "Active path:", None))
        self.calChosepath_B.setText(_translate("MainWindow", "Chose project path", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Calibration:", None))
        self.checkBox_2.setText(_translate("MainWindow", "Use existing calibration for camera(s)", None))
        self.calChoseExisting_B.setText(_translate("MainWindow", "Chose folder", None))
        self.pushButton.setText(_translate("MainWindow", "Clear Table", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Folder setup", None))
        self.groupBox.setTitle(_translate("MainWindow", "Tracking", None))
        self.groupBox_7.setToolTip(_translate("MainWindow", "Video loading functions", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Load single video", None))
        self.trkLoad_B.setText(_translate("MainWindow", "Load Video", None))
        self.trkPreview_B.setText(_translate("MainWindow", "Fast Preview", None))
        self.label_10.setText(_translate("MainWindow", "Video path:", None))
        self.pathLabel.setText(_translate("MainWindow", "No video loaded", None))
        self.trkFramerate_LE.setToolTip(_translate("MainWindow", "set to 27 fps by default", None))
        self.trkFramerate_LE.setText(_translate("MainWindow", "27", None))
        self.trkFramerate_LE.setPlaceholderText(_translate("MainWindow", "Enter framerate", None))
        self.label_2.setText(_translate("MainWindow", "Framerate", None))
        self.label_11.setText(_translate("MainWindow", "Camera ID:", None))
        self.cameraIdLineEdit.setToolTip(_translate("MainWindow", "Enter camera ID (ex. last two digits of IP address)", None))
        self.cameraIdLineEdit.setText(_translate("MainWindow", "10", None))
        self.cameraIdLineEdit.setPlaceholderText(_translate("MainWindow", "10", None))
        self.label_21.setText(_translate("MainWindow", "Help box:", None))
        self.novidCheckBox.setToolTip(_translate("MainWindow", "Will track video, produce an output file if \"Produce output files\" is checked but will not show the video tracking.", None))
        self.novidCheckBox.setText(_translate("MainWindow", "Surpress video", None))
        self.label_control_Playback.setText(_translate("MainWindow", "Control video playback speed:", None))
        self.trkTrack_B.setToolTip(_translate("MainWindow", "Starts object tracking on currently loaded video.", None))
        self.trkTrack_B.setText(_translate("MainWindow", "Track", None))
        self.playbackSlider.setToolTip(_translate("MainWindow", "Speed up or slow down video", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Video processing", None))
        self.groupBox_2.setToolTip(_translate("MainWindow", "Lower limit for detectable contour area in pixels", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filters", None))
        self.medianFilterCheckbox.setToolTip(_translate("MainWindow", "Removes fuzzy noise (slow)", None))
        self.medianFilterCheckbox.setText(_translate("MainWindow", "Apply median filter", None))
        self.gaussCheckBox.setToolTip(_translate("MainWindow", "Smooth out image", None))
        self.gaussCheckBox.setText(_translate("MainWindow", "Use Guassian blur", None))
        self.backgroundCheckBox.setToolTip(_translate("MainWindow", "Necessary for tracking", None))
        self.backgroundCheckBox.setText(_translate("MainWindow", "Apply MOG", None))
        self.gaussSlider.setToolTip(_translate("MainWindow", "Reduce with noise with Gaussian filter", None))
        self.gaussValueLabel.setText(_translate("MainWindow", "0", None))
        self.removeDigitsCheckBox.setToolTip(_translate("MainWindow", "Reduce false detections because of time stamp", None))
        self.removeDigitsCheckBox.setText(_translate("MainWindow", "Remove white digits", None))
        self.label.setText(_translate("MainWindow", "px", None))
        self.label_9.setText(_translate("MainWindow", "px", None))
        self.kernelSlider.setToolTip(_translate("MainWindow", "Choose kernel size for dilate and erode", None))
        self.kernelValueLabel.setText(_translate("MainWindow", "0", None))
        self.erodeCheckbox.setToolTip(_translate("MainWindow", "Useful to erode away noise", None))
        self.erodeCheckbox.setText(_translate("MainWindow", "Erode", None))
        self.dilateCheckbox.setToolTip(_translate("MainWindow", "Useful to increase size of small objects", None))
        self.dilateCheckbox.setText(_translate("MainWindow", "Dilate", None))
        self.medianValueLabel.setText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "px", None))
        self.contourLineEdit.setToolTip(_translate("MainWindow", "Default is 100", None))
        self.contourLineEdit.setText(_translate("MainWindow", "100", None))
        self.trkContour_B.setText(_translate("MainWindow", "Reset contour area limit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tracking", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Post-processing", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "Manual false detection removal", None))
        self.ppBlank_B.setToolTip(_translate("MainWindow", "Removed erroneous data from selected rows in the table.", None))
        self.ppBlank_B.setText(_translate("MainWindow", "Blank selected rows", None))
        self.ppUndo_B.setToolTip(_translate("MainWindow", "Reverts active track back to its orginal state.", None))
        self.ppUndo_B.setText(_translate("MainWindow", "Undo changes to active file", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "Automated false detection removal", None))
        self.removelonersCheckBox_2.setText(_translate("MainWindow", "Remove lone values", None))
        self.rSTDCheckBox_2.setText(_translate("MainWindow", "Perform rSTD removal", None))
        self.label_24.setText(_translate("MainWindow", "rSTD periods", None))
        self.label_25.setText(_translate("MainWindow", "rSTD threshold", None))
        self.ppExecute_B.setText(_translate("MainWindow", "Process", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Import and select", None))
        self.label_4.setText(_translate("MainWindow", "Please select track to edit:", None))
        self.label_3.setText(_translate("MainWindow", "Active file:", None))
        self.ppFileLoaded_L.setText(_translate("MainWindow", "No file specified", None))
        self.csvList_LW.setToolTip(_translate("MainWindow", "Selected item in list is the active file for post-processing. Make sure cameras appear in list in ascending order (i.e. first, second, third camera going upstream).", None))
        self.ppFileOpen_B.setToolTip(_translate("MainWindow", "Select all file for post-processing a single trajectory.", None))
        self.ppFileOpen_B.setText(_translate("MainWindow", "Load files ...", None))
        self.ppClean_B.setToolTip(_translate("MainWindow", "Erases all file create during post-processing from the active directory.", None))
        self.ppClean_B.setText(_translate("MainWindow", "Empty list and revert folder to raw input", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Adjust for timing delay/advance", None))
        self.ppAdjust_B.setText(_translate("MainWindow", "Adjust", None))
        self.ppSubtract_RB.setText(_translate("MainWindow", "Subtract rows", None))
        self.ppAdjust_LE.setText(_translate("MainWindow", "30", None))
        self.label_7.setText(_translate("MainWindow", "Enter # of rows:", None))
        self.ppAdd_RB.setText(_translate("MainWindow", "Add rows", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Single-file Adjust", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Stitching", None))
        self.ppStitch_B.setToolTip(_translate("MainWindow", "Stitches paths from all cameras together", None))
        self.ppStitch_B.setText(_translate("MainWindow", "Stitch", None))
        self.ppHorizontalCombine_B.setToolTip(_translate("MainWindow", "Places camera frames side by side to allow user to evaluate correct overlap", None))
        self.ppHorizontalCombine_B.setText(_translate("MainWindow", "Combine horizontally", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Multi-file stitching", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Cropping and interpolation", None))
        self.ppInterpolate_B.setText(_translate("MainWindow", "Interpolate", None))
        self.cropstartLineEdit_2.setText(_translate("MainWindow", "0", None))
        self.label_22.setText(_translate("MainWindow", "Start Frame:", None))
        self.maLineEdit_2.setToolTip(_translate("MainWindow", "Number of periods for the moving averages", None))
        self.maLineEdit_2.setText(_translate("MainWindow", "10", None))
        self.maLabel_2.setText(_translate("MainWindow", "MA periods:", None))
        self.cropendLineEdit_2.setText(_translate("MainWindow", "0", None))
        self.label_23.setText(_translate("MainWindow", "End Frame:", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Cropping and interpolation", None))
        self.plot_L.setText(_translate("MainWindow", "Trace will appear when a trajectory file is selected ...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Post-processing", None))
        self.activePath_L.setText(_translate("MainWindow", "No path specified", None))
        self.projectPath_L.setText(_translate("MainWindow", "Active Project Path:", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))

